### ISSUE TITLE
Decide on code formatting

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#12]
I'm not a big fan of the formatting changes, especially the if statements (for example in the method `create()`). Ideally keep formatting as was and then agree on some code style and formatting standard - this applies just to the changes made in GUI.py

_Originally posted by @miskfi in https://github.com/stepva/chatalysis/pull/11#pullrequestreview-1048652168_

**Comment by stepva** [comment]
@miskfi try to use black, I like it and vote for it hehe

**Comment by miskfi** [comment]
I really don't like some of the formatting choices in Black - makes the code unnecessarily long and confusing to read. What about [autopep8](https://github.com/peter-evans/autopep8)? I think having a PEP8 compliant code is alright, even if the formatting differs a little bit somewhere. But I respect your preferences, so if you want, Black it is.

Also maybe we could formalize other code aspects as well like docstrings (maybe use some linter like pydocstyle) and type annotations?

**Comment by miskfi** [comment]
Settled on **Black**.
