### ISSUE TITLE
Emoji in chat name (probably) causes Top conversations to not be aligned

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#18]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/43886074/181904356-91de39eb-bb75-4742-915c-2719b84d0b16.png">

I don't know if it is caused by the emoji, but seems likely, all other chats are aligned correctly

**Comment by miskfi** [comment]
Fixed by removing all emoji from the Top conversations output
