### ISSUE TITLE
Files not allowing for refresh with new data after being created once

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#19]
in chatalysis.py, htmllyse() on lines 29-31
```
    if os.path.exists(file):
        wb.open(file)
        return
```

would be good to somehow check for the timestamp of the creation of the file, otherwise when doing it again after a while with new data, the analysis is not run fresh

**Comment by miskfi** [comment]
Yea, good point. Maybe we could compare the number of messages in the generated file vs. current data - I think that's a pretty good indicator of how recent the generated file is.
