### ISSUE TITLE
Nicer GUI (especially on Linux)

### ISSUE THREAD

**Issue by miskfi** [stepva/chatalysis#28]
The GUI looks quite ugly and dated on Linux (and Windows to some degree) - we could experiment with Styles or ttk Themes to make it nicer [(see this)](https://www.reddit.com/r/Python/comments/lps11c/how_to_make_tkinter_look_modern_how_to_use_themes/). However, on macOS the GUI looks pretty nice, so I would like to keep it intact if possible.

**Comment by stepva** [comment]
remember to add the option to choose between two chats with the same name, based on a rough number of messages taken from the number of json files for example

**Comment by miskfi** [comment]
We're running into a lot of issues with Tkinter, most concerning different behavior on various operating systems. I just don't wanna deal with this anymore, therefore I won't be doing any aesthetic updates to the current (tkinter) GUI anymore because you never know how it's gonna behave on Mac, Linux...

Eventually, I will remake the entire GUI in some more reliable framework (probably PyQt5), but I'm not sure when I'll have time to do that.
