### ISSUE TITLE
Incorrect (weird) emojis in group chat after latest data download

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#33]
Only with latest data, these weird colored squares are showing in emoji stats, probably some special emojis (or something else) being parsed incorrectly. Not related to any recent changes in code.

![image](https://user-images.githubusercontent.com/43886074/190871078-925b864a-728c-4913-9e42-93a5a6cedd29.png)

could be worked on together with #31 , looks like the analysis of emojis needs a bigger rework :(

**Comment by miskfi** [comment]
Also look into the hearts emoji - in some conversations the black heart is my top emoji even though I only ever use the read heart.

**Comment by stepva** [comment]
closing - my emojis are correct (RIP Wordle January 2022-January 2022), heart emojis are incorrectly encoded by facebook.
\u00e2\u009d\u00a4 vs  \u00e2\u009d\u00a4\u00ef\u00b8\u008f
I'll fix it when I get a job at Meta, I prosime
