### ISSUE TITLE
People with no emoji appear in the stats

### ISSUE THREAD

**Issue by miskfi** [stepva/chatalysis#37]
People who didn't send any emojis or reactions still appear in the HTML output. Do we want to keep this behavior or do we want to remove them?

![bug](https://user-images.githubusercontent.com/98880683/190890404-536b6f86-e9aa-4dc0-bdf7-a6cbd489acd2.png)

**Comment by stepva** [comment]
Will be done with #17

**Comment by stepva** [comment]
try sorting them for groupchats
