### ISSUE TITLE
Output HTML does not open automatically in browser most of the time

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#4]
Probably an issue with Safari? 
0:97: execution error: Soubor nějaký objekt nebyl nalezen. (-43)
69:77: execution error: „application "chrome"“ nelze načíst. (-1728)

**Comment by stepva** [comment]
reopened, does not open for me on Mac again with the recent changes, will look into it

**Comment by stepva** [comment]
will try to fix this together with #19

**Comment by miskfi** [comment]
#20 should solve this issue. Works on Windows (Chrome, Firefox, Edge) and Linux (Chrome, Firefox) and I suppose @stepva tested it on macOS.
