### ISSUE TITLE
Rework the logic of getting jsons, messages and other info to correctly support downloading additional data

### ISSUE THREAD

**Issue by stepva** [stepva/chatalysis#80]
Chatalysis supports downloading additional messages for a new time interval when user already has downloaded some messages previously. However, this does not work correctly:
- if groupchat changes a name, the jsons will not be combined. But it can be achieved because the latter part of chat_id stays the same (eg. 8boduxf_zb2jbkk66a and 9boduxf_zb2jbkk66a)
- getting participants and title etc. also depends on the file from which it is taken, now it assumes that it's the same in all jsons, which is correct when a user downloads everything at once, but when adding more data after some time this assumption fails. This can be fixed by taking the data from the most recently modified file (os.path.getmtime(x))
- unfortunately it includes also having to rework gui box for selecting conversations (to only include latest conversation names for example) and other parts of the process
- after that is done correctly, we can rework processing messages - ideally I would have "pariticipants" to be the current participants, but for total stats we also need stats from the other names, but without all the extra if statements in the for loop. That will be done easily once the stuff above is handled

**Comment by miskfi** [comment]
I don't see how a GUI rework would be necessary. If the conversation is identified only by the most recent ID, only those names will be displayed.

But I assume that the data loading stage would take care of this problem - load all the messages under just one (the most recent) name.

**Comment by stepva** [comment]
notes:
edge cases to check: inbox/6gydyqvvvq
